language: cpp

os: linux
dist: bionic
compiler: clang

addons:
  apt:
    packages:
      - clang-10
      - llvm-10-dev
      - libclang-10-dev
      - libclang-cpp10-dev

env:
 - CLANG=clang++-10

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER="$(which $CLANG)" ..
  - make
  - make test

notifications:
  email: false
