language: cpp

os: linux
dist: focal
compiler: clang

matrix:
  include:
    - addons:
        apt:
          packages:
            - clang-8
            - llvm-8-dev
            - libclang-8-dev
      env:
        - CLANGXX=clang++-8
    - addons:
        apt:
          packages:
            - clang-9
            - llvm-9-dev
            - libclang-9-dev
      env:
        - CLANGXX=clang++-9
    - addons:
        apt:
          packages:
            - clang-10
            - llvm-10-dev
            - libclang-10-dev
            - libclang-cpp10-dev
      env:
        - CLANGXX=clang++-10
    - addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-11
            - llvm-11-dev
            - libclang-11-dev
            - libclang-cpp11-dev
      env:
        - CLANGXX=clang++-11

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER="$(which $CLANGXX)" ..
  - make
  - make test

notifications:
  email: false
