name: build and run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CXX: [clang++-12, clang++-13, clang++-14, clang++-15]
        include:
        - CC: clang-12
          CXX: clang++-12
          LLVM_DEPENDENCIES: clang-12 llvm-12-dev libclang-12-dev libclang-cpp12-dev

        - CC: clang-13
          CXX: clang++-13
          LLVM_DEPENDENCIES: clang-13 llvm-13-dev libclang-13-dev libclang-cpp13-dev

        - CC: clang-14
          CXX: clang++-14
          LLVM_DEPENDENCIES: clang-14 llvm-14-dev libclang-14-dev libclang-cpp14-dev

        - CC: clang-15
          CXX: clang++-15
          LLVM_DEPENDENCIES: clang-15 llvm-15-dev libclang-15-dev libclang-cpp15-dev

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: install-dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install -yq lua5.4 rustc valgrind &&
          sudo apt-get install -yq ${{ matrix.LLVM_DEPENDENCIES }}

      - name: conan-install
        run: >
          pip install conan &&
          conan profile detect &&
          conan install . --output-folder=build --build=missing

      - name: cmake-configure
        run: >
          cmake -B build
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_C_COMPILER=${{ matrix.CC }}
          -DCMAKE_CXX_COMPILER=${{ matrix.CXX }}
          -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
          -DCTEST_USE_VALGRIND=ON

      - name: cmake-build
        run: cmake --build build --parallel $(nproc)

      - name: test-run
        run: cmake --build build --target test
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
