name: build and run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CXX: [clang++-11, clang++-12]
        include:
        - CC: clang-11
          CXX: clang++-11
          LLVM_DEPENDENCIES: clang-11 llvm-11-dev libclang-11-dev libclang-cpp11-dev

        - CC: clang-12
          CXX: clang++-12
          LLVM_DEPENDENCIES: clang-12 llvm-12-dev libclang-12-dev libclang-cpp12-dev

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: install-dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install -yq lua5.4 rustc valgrind &&
          sudo apt-get install -yq ${{ matrix.LLVM_DEPENDENCIES }}

      - name: conan-install
        run: >
          pip install conan &&
          conan install . --output-folder=build --build=missing

      - name: cmake-configure
        run: >
          cmake -B build
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_C_COMPILER=${{ matrix.CC }}
          -DCMAKE_CXX_COMPILER=${{ matrix.CXX }}
          -DCTEST_USE_VALGRIND=ON

      - name: cmake-build
        run: cmake --build build --parallel $(nproc)

      - name: test-run
        run: cmake --build build --target test
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
