name: build and run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CXX: [clang++-8, clang++-9, clang++-10]
        include:
        - CC: clang-8
          CXX: clang++-8
          LLVM_DEPENDENCIES: clang-8 llvm-8-dev libclang-8-dev

        - CC: clang-9
          CXX: clang++-9
          LLVM_DEPENDENCIES: clang-9 llvm-9-dev libclang-9-dev

        - CC: clang-10
          CXX: clang++-10
          LLVM_DEPENDENCIES: clang-10 llvm-10-dev libclang-10-dev libclang-cpp10-dev

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: install-dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install -yq libboost-dev libboost-graph-dev libboost-regex-dev lua5.3 lua5.3-dev valgrind &&
          sudo apt-get install -yq ${{ matrix.LLVM_DEPENDENCIES }}

      - name: cmake-configure
        run: >
          cmake -B build
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_C_COMPILER=${{ matrix.CC }}
          -DCMAKE_CXX_COMPILER=${{ matrix.CXX }}
          -DCTEST_USE_VALGRIND=ON

      - name: cmake-build
        run: cmake --build build --parallel $(nproc)

      - name: test-run
        run: cmake --build build --target test
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
